application:
  subdomain: picoclaw
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://picoclaw:18800/
services:
  picoclaw:
    #  ghcr.io/sipeed/picoclaw:v0.2.9-launcher
    # upstream: ghcr.io/sipeed/picoclaw:v0.3.1-launcher
    image: registry.lazycat.cloud/czyt/sipeed/picoclaw:a2bc3ccac81b97ea
    environment:
      - PICOCLAW_GATEWAY_HOST=0.0.0.0
      - TZ={{.U.timezone}}
      - PICOCLAW_LAUNCHER_TOKEN={{.U.launcher_token}}
    binds:
      - /lzcapp/var/data:/root/.picoclaw
